language: cpp
sudo: false
compiler:
  - clang++
  - g++
before_install:
  - chmod u+x get_dependencies.sh
  - ./get_dependencies.sh

script:
  - cp CppNumericalSolvers.config.example CppNumericalSolvers.config
  - mkdir build
  - cd build
  - cmake ..
  - make all
  - make lint
  - ./bin/verify

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

notifications:
  email: false
